apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-volume-workspace
  labels:
    airbyte: volume-workspace
spec:
  storageClassName: block-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
