apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-volume-db
  labels:
    airbyte: volume-db
spec:
  storageClassName: block-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
