{{- if and .Values.scheduler.enabled .Values.scheduler.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  metadata:
  labels:
    {{- include "airbyte.scheduler.labels" . | nindent 4 }}
  name: {{ template "airbyte.serviceAccountName.scheduler" . }}
  namespace: {{ template "airbyte.namespace" . }}
{{- end -}}