{{- if .Values.server.enabled }}
apiVersion: {{ template "airbyte.deployment.apiVersion" . }}
kind: Deployment
metadata:
{{- if .Values.server.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.server.deploymentAnnotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "airbyte.server.labels" . | nindent 4 }}
    component: server
  name: {{ template "airbyte.fullname" . }}-{{ .Values.server.name }}
  namespace: {{ template "airbyte.namespace" . }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "airbyte.server.matchLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.server.podAnnotations }}
      annotations:
        {{ toYaml .Values.server.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "airbyte.server.labels" . | nindent 8 }}
        {{- if .Values.server.podLabels}}
        {{ toYaml .Values.server.podLabels | nindent 8 }}
        {{- end}}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: airbyte
                    operator: In
                    values:
                      - scheduler
              topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ template "airbyte.fullname" . }}-{{ .Values.server.name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: "{{ .Values.db.image.pullPolicy }}"
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: {{ template "airbyte.fullname" . }}-volume-configs
              mountPath: /configs
            - name: {{ template "airbyte.fullname" . }}-volume-workspace
              mountPath: /workspace
          env:
            {{- range $key, $value := .Values.server.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            # TODO - Other Env variables
          resources:
            {{ toYaml .Values.server.resources | indent 12 }}
      volumes:
        - name: {{ template "airbyte.fullname" . }}-volume-workspace
          persistentVolumeClaim:
            claimName: {{ template "airbyte.fullname" . }}-volume-workspace
        - name: {{ template "airbyte.fullname" . }}-volume-configs
          persistentVolumeClaim:
            claimName: {{ template "airbyte.fullname" . }}-volume-configs
{{- end }}