{{- if .Values.temporal.enabled }}
apiVersion: {{ template "airbyte.deployment.apiVersion" . }}
kind: Deployment
metadata:
{{- if .Values.temporal.deploymentAnnotations }}
  annotations:
    {{ toYaml .Values.temporal.deploymentAnnotations | nindent 4 }}
{{- end }}
  labels:
    {{- include "airbyte.temporal.labels" . | nindent 4 }}
    component: temporal
  name: {{ template "airbyte.fullname" . }}-{{ .Values.temporal.name }}
  namespace: {{ template "airbyte.namespace" . }}
spec:
  replicas: {{ .Values.temporal.replicaCount }}
  selector:
    matchLabels:
      {{- include "airbyte.temporal.matchLabels" . | nindent 6 }}
  template:
    metadata:
    {{- if .Values.temporal.podAnnotations }}
      annotations:
        {{ toYaml .Values.temporal.podAnnotations | nindent 8 }}
    {{- end }}
      labels:
        {{- include "airbyte.temporal.labels" . | nindent 8 }}
        {{- if .Values.temporal.podLabels}}
        {{ toYaml .Values.temporal.podLabels | nindent 8 }}
        {{- end}}
    spec:
      containers:
        - name: {{ template "airbyte.fullname" . }}-{{ .Values.temporal.name }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: "{{ .Values.db.image.pullPolicy }}"
          ports:
            - containerPort: 7233
          volumeMounts:
            - name: {{ template "airbyte.fullname" . }}-volume-configs
              mountPath: /configs
            - name: {{ template "airbyte.fullname" . }}-volume-workspace
              mountPath: /workspace
          env:
            {{- range $key, $value := .Values.temporal.extraEnv }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
            # TODO - Other Env variables
          resources:
            {{ toYaml .Values.temporal.resources | indent 12 }}
      volumes:
        - name: {{ template "airbyte.fullname" . }}-volume-workspace
          persistentVolumeClaim:
            claimName: {{ template "airbyte.fullname" . }}-volume-workspace
        - name: {{ template "airbyte.fullname" . }}-volume-configs
          persistentVolumeClaim:
            claimName: {{ template "airbyte.fullname" . }}-volume-configs
{{- end }}